### ISSUE TITLE
有关scheduler_config.json文件

### ISSUE THREAD

**Issue by houruixiang-1024** [hyao1/GLAD#1]
Traceback (most recent call last):
  File "main.py", line 522, in <module>
    dino_model, val_pipe = load_test_model(args, torch.float16)
  File "main.py", line 393, in load_test_model
    scheduler=DDIMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler"),
  File "/data/greatwall13/anaconda3/envs/unsup/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 140, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/data/greatwall13/anaconda3/envs/unsup/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 397, in load_config
    raise EnvironmentError(
OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named scheduler_config.json.

**Comment by hyao1** [comment]
CompVis/stable-diffusion-v1-4 is pretrained stable diffusion model. You need to download it before training. If you can not download it becasue of network, we provide it in our [onedrive](https://stuhiteducn-my.sharepoint.com/:f:/g/personal/23b903042_stu_hit_edu_cn/Etg1bdDSnOZBt7AydlkCzMUBYKxgmM_9tB-g5M70PJhAVQ) REAMDME.md. After downloading it, please modify the args.pretrained_model_name_or_path into your downloaded file path.
